info:
  app:
    name: API Gateway
    version: 1.0.0
    description: Social Core API Gateway
    author: Vivek Pandey

server:
  port: 3000

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: auth-service
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/api/auth/**

            - id: chat-service
              uri: lb://CHAT-SERVICE
              predicates:
                - Path=/api/chat/**

            - id: reel-service
              uri: lb://REEL-SERVICE
              predicates:
                - Path=/api/reels/**

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  info:
    env:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka